### ISSUE TITLE
Store paths for rejected files in import_files()

### ISSUE THREAD

**Issue by alexipeck** [alexipeck/tlm#14]

**Comment by ryancarins** [comment]
What is the rationale for this again? I did a quick read and it looks like all we're filtering out is directories (not that many) to make sure that each item is a regular file. And we test if the extension is allowed, and I assume we would want to keep reading those in case there is an extension that we want that the user hasn't whitelisted. And it would be more checks anyway right? Just that we'd have to check that every file wasn't an ignored file?
