### ISSUE TITLE
Investigate .tlm_config resetting

### ISSUE THREAD

**Issue by ryancarins** [alexipeck/tlm#20]
Alexi's config file was randomly reset to default for some reason on commit 67db5fc93812db7384be6e80be4158b2bd2b656b
I suspect that this is something to do with the config being created only if it couldn't be read but not checking the kind of error.
Likely hard to reproduce but will need to investigate

**Comment by alexipeck** [comment]
Nah, it was just stashed, I did an oopsie when I checked out a really old commit, I stashed the changes to switch branch.
